### ISSUE TITLE
Posthtml website for docs and other details

### ISSUE THREAD

**Issue by anikethsaha** [posthtml/posthtml.org#3]
update
---
The new posthtml website from [`posthtml.org`](https://github.com/posthtml/posthtml.org) is **live**

🎉 Preview at  https://posthtml-org.now.sh/#/
🔨 Made using @docsify
🚀 Deployed at Zeit

Original Issue
---

## I have created [posthtml website](https://posthtml-website.netlify.com/) using @docsifyjs .
Its an unofficial docs site.

**I am proposing if we can continue the development of this site in order to make it the official**

Its been developed in a private git repo. and would love to invite the collaborators of posthtml and others as well in order to have a look at the source code.

Lets discuss ⭐️

**Comment by voischev** [comment]
🥇
