### ISSUE TITLE
fix: incorrect protocol for image

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml.org#5]
Firefox speaks of insecurity due to a picture that has the wrong protocol `http://posthtml.github.io/posthtml/logo.svg`

**Comment by anikethsaha** [comment]
I will change that soon 👍

**Comment by anikethsaha** [comment]
done https://github.com/posthtml/posthtml.org/commit/60284f9fcf62c53a5ae995b23ec0c7ed0f8fdd0b
